<?php
if (!defined('_GNUBOARD_'))
    exit; // 개별 페이지 접근 불가

// add_stylesheet('css 구문', 출력순서); 숫자가 작을 수록 먼저 출력됨
add_stylesheet('<link rel="stylesheet" href="' . $board_skin_url . '/style.css?v=' . time() . '">', 0);
?>

<section id="bo_w" class="skin-container">
    <h2 class="sound_only"><?php echo $g5['title'] ?></h2>

    <!-- 게시물 작성/수정 시작 { -->
    <?php
    $action_url_final = $action_url;
    if (isset($_GET['me_code'])) {
        $action_url_final .= '?' . 'me_code=' . urlencode($_GET['me_code']);
        // Note: $action_url usually ends with .php, if it has params already we need logic, but write_update.php usually doesn't have params.
        // Safer: check if ? exists.
        if (strpos($action_url, '?') !== false) {
            $action_url_final = $action_url . '&me_code=' . urlencode($_GET['me_code']);
        } else {
            $action_url_final = $action_url . '?me_code=' . urlencode($_GET['me_code']);
        }
    }
    ?>
    <form name="fwrite" id="fwrite" action="<?php echo $action_url_final ?>" onsubmit="return fwrite_submit(this);"
        method="post" enctype="multipart/form-data" autocomplete="off" style="width:<?php echo $width; ?>">
        <input type="hidden" name="uid" value="<?php echo get_uniqid(); ?>">
        <input type="hidden" name="w" value="<?php echo $w ?>">
        <input type="hidden" name="bo_table" value="<?php echo $bo_table ?>">
        <input type="hidden" name="wr_id" value="<?php echo $wr_id ?>">
        <input type="hidden" name="sca" value="<?php echo $sca ?>">
        <input type="hidden" name="sfl" value="<?php echo $sfl ?>">
        <input type="hidden" name="stx" value="<?php echo $stx ?>">
        <input type="hidden" name="spt" value="<?php echo $spt ?>">
        <input type="hidden" name="sst" value="<?php echo $sst ?>">
        <input type="hidden" name="sod" value="<?php echo $sod ?>">
        <input type="hidden" name="page" value="<?php echo $page ?>">
        <input type="hidden" name="me_code" value="<?php echo isset($_GET['me_code']) ? $_GET['me_code'] : ''; ?>">
        <?php if ($is_category) { ?>
            <div class="bo_w_select write_div" style="scroll-margin-top: 130px;">
                <label for="ca_name">분류 선택<span class="required-ico"></span></label>
                <!-- Hidden Input for Gnuboard standard ca_name -->
                <input type="text" name="ca_name" id="ca_name"
                    value="<?php echo isset($write['ca_name']) ? $write['ca_name'] : ''; ?>" required style="display:none;">

                <!-- Hidden Input for Category Code (wr_1) -->
                <input type="hidden" name="wr_1" id="wr_1_code"
                    value="<?php echo isset($write['wr_1']) ? $write['wr_1'] : ''; ?>">

                <!-- Cascading Select Container -->
                <div id="category_container" class="category-wrapper" style="scroll-margin-top: 130px;">
                    <!-- Dropdowns generated by JS -->
                </div>
            </div>

            <style>
                .category-wrapper {
                    display: flex;
                    gap: 12px;
                    width: 100%;
                    margin-bottom: 24px;
                    flex-wrap: wrap;
                }

                .product-category-select {
                    flex: 1;
                    min-width: 150px;
                    display: block;
                    background: #fff;
                    color: #333;
                    border: 1px solid #ddd;
                    border-radius: 4px;
                    padding: 10px;
                    font-size: 14px;
                }

                @media (max-width: 768px) {
                    .category-wrapper {
                        flex-direction: column;
                        gap: 8px;
                    }
                }
            </style>

            <script>
                $(document).ready(function () {
                    initCascadingCategory("<?php echo $bo_table; ?>");
                });

                function initCascadingCategory(boTable) {
                    var $originalSelect = $("#ca_name");
                    var $codeStorage = $("#wr_1_code");
                    var $wrap = $("#category_container");
                    // Safe PHP Output
                    var initialCaName = "<?php echo isset($write['ca_name']) ? addslashes($write['ca_name']) : ''; ?>";
                    var initialCode = "<?php echo isset($write['wr_1']) ? $write['wr_1'] : ''; ?>";
                    var validCategories = <?php echo json_encode(explode('|', $board['bo_category_list']), JSON_UNESCAPED_UNICODE); ?>;

                    // Fetch Tree Data
                    $.ajax({
                        url: "<?php echo G5_PLUGIN_URL; ?>/tree_category/ajax_get_tree.php",
                        data: { bo_table: boTable },
                        dataType: "json",
                        success: function (res) {
                            if (!res.success || !res.data || res.data.length === 0) {
                                $originalSelect.show(); // Fallback
                                return;
                            }

                            // Process Data into Tree Structure
                            var treeData = buildTree(res.data);
                            var hiddenRootName = "";

                            // SEARCH FOR ROOT UNWRAPPING
                            // If the tree has only 1 top-level node (e.g., "시공사례"), and it has children,
                            // we probably want to start selection from the children (e.g., "RESIDENCE").
                            if (treeData.length === 1 && treeData[0].children && treeData[0].children.length > 0) {
                                hiddenRootName = treeData[0].name;
                                treeData = treeData[0].children;
                            }

                            renderCascadingSelects(treeData, $wrap, $originalSelect, $codeStorage, initialCaName, initialCode, validCategories, hiddenRootName);
                        },
                        error: function () {
                            $originalSelect.show();
                        }
                    });
                }

                function buildTree(flatData) {
                    var map = {};
                    var tree = [];
                    flatData.forEach(function (node) {
                        map[node.code] = { ...node, children: [] };
                    });
                    // Sort by code or order? Assuming sorted from server
                    flatData.forEach(function (node) {
                        if (node.parent && node.parent !== 'root' && map[node.parent]) {
                            map[node.parent].children.push(map[node.code]);
                        } else {
                            tree.push(map[node.code]);
                        }
                    });
                    return tree;
                }

                function renderCascadingSelects(treeData, $container, $originalSelect, $codeStorage, initialCaName, initialCode, validCategories, hiddenRootName) {
                    // Initialize Selects with existing styles
                    var $depth1 = $("<select class='product-category-select dynamic-cate'><option value=''>대분류 선택</option></select>");
                    var $depth2 = $("<select class='product-category-select dynamic-cate' style='display:none;'><option value=''>중분류 선택</option></select>");
                    var $depth3 = $("<select class='product-category-select dynamic-cate' style='display:none;'><option value=''>소분류 선택</option></select>");

                    $container.empty().append($depth1, $depth2, $depth3);

                    // Populate Depth 1
                    treeData.forEach(function (node) {
                        $depth1.append(new Option(node.name, node.code));
                    });

                    function findNode(nodes, code) {
                        for (var i = 0; i < nodes.length; i++) {
                            if (nodes[i].code == code) return nodes[i];
                            if (nodes[i].children) {
                                var found = findNode(nodes[i].children, code);
                                if (found) return found;
                            }
                        }
                        return null;
                    }

                    $depth1.on("change", function () {
                        var val = $(this).val();
                        $depth2.empty().append(new Option("중분류 선택", "")).hide();
                        $depth3.empty().append(new Option("소분류 선택", "")).hide();

                        if (val) {
                            var node = findNode(treeData, val);
                            if (node && node.children.length > 0) {
                                node.children.forEach(function (child) {
                                    $depth2.append(new Option(child.name, child.code));
                                });
                                $depth2.show();
                            }
                        }
                        updateFinalValues();
                    });

                    $depth2.on("change", function () {
                        var val = $(this).val();
                        $depth3.empty().append(new Option("소분류 선택", "")).hide();

                        if (val) {
                            var parentVal = $depth1.val();
                            var parentNode = findNode(treeData, parentVal);
                            if (parentNode) {
                                var node = findNode(parentNode.children, val);
                                if (node && node.children.length > 0) {
                                    node.children.forEach(function (child) {
                                        $depth3.append(new Option(child.name, child.code));
                                    });
                                    $depth3.show();
                                }
                            }
                        }
                        updateFinalValues();
                    });

                    $depth3.on("change", function () {
                        updateFinalValues();
                    });

                    function updateFinalValues() {
                        var d1 = $depth1.val();
                        var d2 = $depth2.val();
                        var d3 = $depth3.val();

                        var lastCode = d3 || d2 || d1;
                        $codeStorage.val(lastCode);

                        // Construct Name Path
                        var parts = [];
                        if (d1) parts.push($depth1.find("option:selected").text());
                        if (d2) parts.push($depth2.find("option:selected").text());
                        if (d3) parts.push($depth3.find("option:selected").text());

                        // Try patterns to match Valid Categories
                        var pathSpace = parts.join(" > "); // Standard "A > B"
                        var pathNoSpace = parts.join(">"); // Compact "A>B"
                        var pathTrimmed = parts.map(s => s.trim()).join(">"); // "A>B" safety

                        var finalVal = pathSpace; // Default

                        // Check existence in validCategories
                        if (validCategories && validCategories.length > 0) {
                            function check(p) {
                                for (var i = 0; i < validCategories.length; i++) {
                                    if (validCategories[i] === p) return true;
                                }
                                return false;
                            }

                            // 1. Exact Match
                            if (check(pathSpace)) { finalVal = pathSpace; }
                            else if (check(pathNoSpace)) { finalVal = pathNoSpace; }
                            // 2. Hidden Root Prefix
                            else if (hiddenRootName) {
                                var withRoot = hiddenRootName + " > " + pathSpace;
                                if (check(withRoot)) { finalVal = withRoot; }
                            }

                            // 3. Fail-safe: Suffix Match (e.g. valid "ABC > RESIDENCE" matches user "RESIDENCE")
                            // Only if we haven't found a match yet
                            if (finalVal === pathSpace && !check(finalVal)) {
                                var suffixSpace = " > " + pathSpace;
                                var suffixNoSpace = ">" + pathNoSpace;
                                for (var i = 0; i < validCategories.length; i++) {
                                    var vc = validCategories[i];
                                    if (vc.indexOf(suffixSpace) !== -1 && vc.indexOf(suffixSpace) === vc.length - suffixSpace.length) {
                                        finalVal = vc; break;
                                    }
                                    if (vc.indexOf(suffixNoSpace) !== -1 && vc.indexOf(suffixNoSpace) === vc.length - suffixNoSpace.length) {
                                        finalVal = vc; break;
                                    }
                                }
                            }
                        }

                        // If not matched, we still set it (server might reject, but we tried)
                        $originalSelect.val(finalVal);
                    }

                    // Initial Load Logic...
                    var urlParams = new URLSearchParams(window.location.search);
                    var targetCode = urlParams.get('me_code') || urlParams.get('cate') || initialCode;

                    if (targetCode) {
                        var seg1 = targetCode.substring(0, 2);
                        if (seg1.length === 2 && $depth1.find("option[value='" + seg1 + "']").length) {
                            $depth1.val(seg1).trigger("change");
                            if (targetCode.length >= 4) {
                                var seg2 = targetCode.substring(0, 4);
                                $depth2.val(seg2).trigger("change");
                                if (targetCode.length >= 6) {
                                    var seg3 = targetCode.substring(0, 6);
                                    $depth3.val(seg3).trigger("change");
                                }
                            }
                        }
                    } else if (initialCaName) {
                        // Fallback logic
                    }
                }
            </script>
        <?php } ?>

        <?php
        $option = '';
        $option_hidden = '';
        if ($is_notice || $is_html || $is_secret || $is_mail) {
            $option = '';
            if ($is_notice) {
                $option .= PHP_EOL . '<li class="chk_box"><input type="checkbox" id="notice" name="notice"  class="selec_chk" value="1" ' . $notice_checked . '>' . PHP_EOL . '<label for="notice"><span></span>공지</label></li>';
            }
            if ($is_html) {
                if ($is_dhtml_editor) {
                    $option_hidden .= '<input type="hidden" value="html1" name="html">';
                } else {
                    $option .= PHP_EOL . '<li class="chk_box"><input type="checkbox" id="html" name="html" onclick="html_auto_br(this);" class="selec_chk" value="' . $html_value . '" ' . $html_checked . '>' . PHP_EOL . '<label for="html"><span></span>html</label></li>';
                }
            }
            if ($is_secret) {
                if ($is_admin || $is_secret == 1) {
                    $option .= PHP_EOL . '<li class="chk_box"><input type="checkbox" id="secret" name="secret"  class="selec_chk" value="secret" ' . $secret_checked . '>' . PHP_EOL . '<label for="secret"><span></span>비밀글</label></li>';
                } else {
                    $option_hidden .= '<input type="hidden" name="secret" value="secret">';
                }
            }
            if ($is_mail) {
                $option .= PHP_EOL . '<li class="chk_box"><input type="checkbox" id="mail" name="mail"  class="selec_chk" value="mail">' . PHP_EOL . '<label for="mail"><span></span>답변메일받기</label></li>';
            }
        }
        echo $option_hidden;
        ?>

        <div class="bo_w_info write_div">
            <?php if ($is_name) { ?>
                <label for="wr_name" class="sound_only">이름<strong>필수</strong></label>
                <input type="text" name="wr_name" value="<?php echo $name ?>" id="wr_name" required
                    class="frm_input half_input required" placeholder="이름">
            <?php } ?>

            <?php if ($is_password) { ?>
                <label for="wr_password" class="sound_only">비밀번호<strong>필수</strong></label>
                <input type="password" name="wr_password" id="wr_password" <?php echo $password_required ?>
                    class="frm_input half_input <?php echo $password_required ?>" placeholder="비밀번호">
            <?php } ?>

            <?php if ($is_email) { ?>
                <label for="wr_email" class="sound_only">이메일</label>
                <input type="text" name="wr_email" value="<?php echo $email ?>" id="wr_email"
                    class="frm_input half_input email " placeholder="이메일">
            <?php } ?>

            <?php if ($is_homepage) { ?>
                <label for="wr_homepage" class="sound_only">홈페이지</label>
                <input type="text" name="wr_homepage" value="<?php echo $homepage ?>" id="wr_homepage"
                    class="frm_input half_input" size="50" placeholder="홈페이지">
            <?php } ?>
        </div>

        <?php if ($option) { ?>
            <div class="write_div">
                <span class="sound_only">옵션</span>
                <ul class="bo_v_option">
                    <?php echo $option ?>
                </ul>
            </div>
        <?php } ?>

        <div class="bo_w_tit write_div">
            <label for="wr_subject" class="sound_only">제목<strong>필수</strong></label>

            <div id="autosave_wrapper" class="write_div">
                <input type="text" name="wr_subject" value="<?php echo $subject ?>" id="wr_subject" required
                    class="frm_input full_input required" size="50" maxlength="255" placeholder="제목">
                <?php if ($is_member) { // 임시 저장된 글 기능 ?>
                    <script src="<?php echo G5_JS_URL; ?>/autosave.js"></script>
                    <?php if ($editor_content_js)
                        echo $editor_content_js; ?>
                    <button type="button" id="btn_autosave" class="btn_frmline">임시 저장된 글 (<span
                            id="autosave_count"><?php echo $autosave_count; ?></span>)</button>
                    <div id="autosave_pop">
                        <strong>임시 저장된 글 목록</strong>
                        <ul></ul>
                        <div><button type="button" class="autosave_close">닫기</button></div>
                    </div>
                <?php } ?>
            </div>
        </div>

        <div class="write_div">
            <label for="wr_content" class="sound_only">내용<strong>필수</strong></label>
            <div class="wr_content <?php echo $is_dhtml_editor ? $config['cf_editor'] : ''; ?>">
                <?php if ($write_min || $write_max) { ?>
                    <!-- 최소/최대 글자 수 사용 시 -->
                    <p id="char_count_desc">이 게시판은 최소 <strong><?php echo $write_min; ?></strong>글자 이상, 최대
                        <strong><?php echo $write_max; ?></strong>글자 이하까지 글을 쓰실 수 있습니다.
                    </p>
                <?php } ?>
                <?php echo $editor_html; // 에디터 사용시는 에디터로, 아니면 textarea 로 노출 ?>
                <?php if ($write_min || $write_max) { ?>
                    <!-- 최소/최대 글자 수 사용 시 -->
                    <div id="char_count_wrap"><span id="char_count"></span>글자</div>
                <?php } ?>
            </div>

        </div>

        <?php for ($i = 1; $is_link && $i <= G5_LINK_COUNT; $i++) { ?>
            <div class="bo_w_link write_div">
                <label for="wr_link<?php echo $i ?>"><i class="fa fa-link" aria-hidden="true"></i><span class="sound_only">
                        링크 #<?php echo $i ?></span></label>
                <input type="text" name="wr_link<?php echo $i ?>" value="<?php if ($w == "u") {
                       echo $write['wr_link' . $i];
                   } ?>" id="wr_link<?php echo $i ?>" class="frm_input full_input" size="50">
            </div>
        <?php } ?>

        <?php for ($i = 0; $is_file && $i < $file_count; $i++) { ?>
            <div class="bo_w_flie write_div">
                <div class="file_wr write_div">
                    <label for="bf_file_<?php echo $i + 1 ?>" class="lb_icon"><i class="fa fa-folder-open"
                            aria-hidden="true"></i><span class="sound_only"> 파일 #<?php echo $i + 1 ?></span></label>
                    <input type="file" name="bf_file[]" id="bf_file_<?php echo $i + 1 ?>"
                        title="파일첨부 <?php echo $i + 1 ?> : 용량 <?php echo $upload_max_filesize ?> 이하만 업로드 가능"
                        class="frm_file ">
                </div>
                <?php if ($is_file_content) { ?>
                    <input type="text" name="bf_content[]" value="<?php echo ($w == 'u') ? $file[$i]['bf_content'] : ''; ?>"
                        title="파일 설명을 입력해주세요." class="full_input frm_input" size="50" placeholder="파일 설명을 입력해주세요.">
                <?php } ?>

                <?php if ($w == 'u' && $file[$i]['file']) { ?>
                    <span class="file_del">
                        <input type="checkbox" id="bf_file_del<?php echo $i ?>" name="bf_file_del[<?php echo $i; ?>]" value="1">
                        <label
                            for="bf_file_del<?php echo $i ?>"><?php echo $file[$i]['source'] . '(' . $file[$i]['size'] . ')'; ?>
                            파일
                            삭제</label>
                    </span>
                <?php } ?>

            </div>
        <?php } ?>


        <?php if ($is_use_captcha) { //자동등록방지  ?>
            <div class="write_div">
                <?php echo $captcha_html ?>
            </div>
        <?php } ?>

        <div class="btn_confirm write_div">
            <?php
            $cancel_href = get_pretty_url($bo_table);
            if (isset($_GET['me_code'])) {
                $cancel_href .= (strpos($cancel_href, '?') !== false ? '&' : '?') . 'me_code=' . urlencode($_GET['me_code']);
            }
            ?>
            <a href="<?php echo $cancel_href; ?>" class="btn_cancel btn">취소</a>
            <button type="submit" id="btn_submit" accesskey="s" class="btn_submit btn">작성완료</button>
        </div>
    </form>

    <script>
        <?php if ($write_min || $write_max) { ?>
            // 글자수 제한
            var char_min = parseInt(<?php echo $write_min; ?>); // 최소
            var char_max = parseInt(<?php echo $write_max; ?>); // 최대
            check_byte("wr_content", "char_count");

            $(function () {
                $("#wr_content").on("keyup", function () {
                    check_byte("wr_content", "char_count");
                });
            });

        <?php } ?>
        function html_auto_br(obj) {
            if (obj.checked) {
                result = confirm("자동 줄바꿈을 하시겠습니까?\n\n자동 줄바꿈은 게시물 내용중 줄바뀐 곳을<br>태그로 변환하는 기능입니다.");
                if (result)
                    obj.value = "html2";
                else
                    obj.value = "html1";
            }
            else
                obj.value = "";
        }

        function fwrite_submit(f) {
            <?php echo $editor_js; // 에디터 사용시 자바스크립트에서 내용을 폼필드로 넣어주며 내용이 입력되었는지 검사함   ?>

            var subject = "";
            var content = "";
            $.ajax({
                url: g5_bbs_url + "/ajax.filter.php",
                type: "POST",
                data: {
                    "subject": f.wr_subject.value,
                    "content": f.wr_content.value
                },
                dataType: "json",
                async: false,
                cache: false,
                success: function (data, textStatus) {
                    subject = data.subject;
                    content = data.content;
                }
            });

            if (subject) {
                alert("제목에 금지단어('" + subject + "')가 포함되어있습니다");
                f.wr_subject.focus();
                return false;
            }

            if (content) {
                alert("내용에 금지단어('" + content + "')가 포함되어있습니다");
                if (typeof (ed_wr_content) != "undefined")
                    ed_wr_content.returnFalse();
                else
                    f.wr_content.focus();
                return false;
            }

            if (document.getElementById("char_count")) {
                if (char_min > 0 || char_max > 0) {
                    var cnt = parseInt(check_byte("wr_content", "char_count"));
                    if (char_min > 0 && char_min > cnt) {
                        alert("내용은 " + char_min + "글자 이상 쓰셔야 합니다.");
                        return false;
                    }
                    else if (char_max > 0 && char_max < cnt) {
                        alert("내용은 " + char_max + "글자 이하로 쓰셔야 합니다.");
                        return false;
                    }
                }
            }

            <?php echo $captcha_js; // 캡챠 사용시 자바스크립트에서 입력된 캡챠를 검사함  ?>

            document.getElementById("btn_submit").disabled = "disabled";

            return true;
        }
    </script>
</section>
<!-- } 게시물 작성/수정 끝 -->