<?php
if (!defined('_GNUBOARD_'))
    exit; // 개별 페이지 접근 불가
include_once(G5_LIB_PATH . '/thumbnail.lib.php');

add_stylesheet('<link rel="stylesheet" href="' . $board_skin_url . '/style.css?v=' . time() . '">', 0);
add_stylesheet('<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600&family=Playfair+Display:ital,wght@0,400;0,600;1,400&display=swap" rel="stylesheet">', 0);
add_javascript('<script src="' . G5_THEME_URL . '/js/category_cascade.js?v=' . time() . '"></script>', 0);
?>







<!-- 그누보드 필수 Hidden Fields -->
<section id="bo_w" class="skin-container">
    <form name="fwrite" id="fwrite" action="<?php echo $action_url ?>" onsubmit="return fwrite_submit(this);"
        method="post" enctype="multipart/form-data" autocomplete="off" class="write-form">
        <input type="hidden" name="uid" value="<?php echo get_uniqid(); ?>">
        <input type="hidden" name="w" value="<?php echo $w ?>">
        <input type="hidden" name="bo_table" value="<?php echo $bo_table ?>">
        <input type="hidden" name="wr_id" value="<?php echo $wr_id ?>">
        <input type="hidden" name="sca" value="<?php echo $sca ?>">
        <input type="hidden" name="sfl" value="<?php echo $sfl ?>">
        <input type="hidden" name="stx" value="<?php echo $stx ?>">
        <input type="hidden" name="page" value="<?php echo $page ?>">
        <?php if (isset($_GET['me_code'])) { ?>
            <input type="hidden" name="me_code" value="<?php echo $_GET['me_code']; ?>">
        <?php } ?>

        <div class="form-group">
            <label class="form-label">Category</label>
            <?php if ($is_category) { ?>
                <!-- Hidden Input for Gnuboard standard ca_name -->
                <input type="text" name="ca_name" id="ca_name"
                    value="<?php echo isset($write['ca_name']) ? $write['ca_name'] : ''; ?>" required style="display:none;">

                <!-- Hidden Input for Category Code (wr_1) -->
                <input type="hidden" name="wr_1" id="wr_1"
                    value="<?php echo isset($write['wr_1']) ? $write['wr_1'] : ''; ?>">

                <!-- Cascading Select Container -->
                <div id="category_container" class="category-wrapper" style="display:flex; gap:10px;">
                    <!-- Dropdowns generated by JS -->
                </div>

                <script>
                    $(document).ready(function () {
                        if (typeof initCascadingCategory === 'function') {
                            initCascadingCategory({
                                bo_table: "<?php echo $bo_table; ?>",
                                ajaxUrl: "<?php echo G5_PLUGIN_URL; ?>/tree_category/ajax_get_tree.php",
                                initialCaName: "<?php echo isset($write['ca_name']) ? addslashes($write['ca_name']) : ''; ?>",
                                initialCode: "<?php echo isset($write['wr_1']) ? $write['wr_1'] : ''; ?>",
                                validCategories: <?php echo json_encode(explode('|', $board['bo_category_list']), JSON_UNESCAPED_UNICODE); ?>
                            });
                        } else {
                            console.error("initCascadingCategory not found");
                            $("#ca_name").show();
                        }
                    });
                </script>
            <?php } ?>
        </div>

        <div class="form-group">
            <label class="form-label">Title</label>
            <input type="text" name="wr_subject" value="<?php echo $subject ?>" id="wr_subject" required
                class="form-input" placeholder="Enter a captivating title">
        </div>

        <div class="form-group">
            <label class="form-label">Cover Image (Main)</label>
            <div class="file-drop-zone" id="drop_zone_0">
                <input type="file" name="bf_file[]" id="bf_file_0" class="input-file" accept="image/*"
                    title="파일첨부 1 : 용량 <?php echo $upload_max_filesize ?> 이하만 업로드 가능">
                <!-- Initial State -->
                <div class="drop-content">
                    <div class="drop-icon">📷</div>
                    <div class="drop-txt">Click to upload your main image (Cover)</div>
                </div>
                <!-- Preview State -->
                <div class="drop-preview" style="display:none;">
                    <img id="preview_0" src="" alt="Main Cover Preview">
                </div>
            </div>

            <script>
                document.getElementById('bf_file_0').addEventListener('change', function (event) {
                    var file = event.target.files[0];
                    if (file) {
                        var reader = new FileReader();
                        reader.onload = function (e) {
                            var zone = document.getElementById('drop_zone_0');
                            zone.querySelector('.drop-content').style.display = 'none';

                            var preview = document.getElementById('preview_0');
                            preview.src = e.target.result;

                            var previewDiv = zone.querySelector('.drop-preview');
                            previewDiv.style.display = 'block';

                            zone.classList.add('has-file');
                        }
                        reader.readAsDataURL(file);
                    }
                });
            </script>
            <?php if ($w == 'u' && $file[0]['file']) { ?>
                <div style="margin-top:10px; color:#aaa;">
                    <input type="checkbox" name="bf_file_del[0]" value="1"> <label for="bf_file_del[0]">
                        <?php echo $file[0]['source'] . '(' . $file[0]['size'] . ')'; ?> 파일 삭제
                    </label>
                </div>
            <?php } ?>
        </div>

        <!-- Additional Images (Gallery) -->
        <div class="form-group">
            <label class="form-label">Gallery Images</label>
            <div class="gallery-upload-grid">
                <?php for ($i = 1; $i < $file_count; $i++) { ?>
                    <div class="file-drop-zone small" id="drop_zone_<?php echo $i; ?>">
                        <input type="file" name="bf_file[]" id="bf_file_<?php echo $i; ?>" class="input-file"
                            accept="image/*"
                            title="파일첨부 <?php echo $i + 1 ?> : 용량 <?php echo $upload_max_filesize ?> 이하만 업로드 가능">

                        <!-- Initial -->
                        <div class="drop-content">
                            <div class="drop-icon" style="font-size:24px;">+</div>
                            <div class="drop-txt" style="font-size:0.8rem;">Add Image <?php echo $i; ?></div>
                        </div>

                        <!-- Preview -->
                        <div class="drop-preview" style="display:none;">
                            <img id="preview_<?php echo $i; ?>" src="" alt="Preview <?php echo $i; ?>">
                        </div>

                        <?php if ($w == 'u' && $file[$i]['file']) { ?>
                            <div class="file-exists-indicator">
                                <span>Saved</span>
                                <input type="checkbox" name="bf_file_del[<?php echo $i ?>]" value="1"
                                    id="file_del_<?php echo $i; ?>">
                                <label for="file_del_<?php echo $i; ?>">Del</label>
                            </div>
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>
        </div>

        <script>
            // Unified Image Preview Logic
            document.querySelectorAll('.input-file').forEach(input => {
                input.addEventListener('change', function (event) {
                    var inputId = event.target.id;
                    // Expected id format: bf_file_0, bf_file_1, ...
                    var index = inputId.replace('bf_file_', '');
                    var zone = document.getElementById('drop_zone_' + index);
                    var file = event.target.files[0];

                    if (file) {
                        var reader = new FileReader();
                        reader.onload = function (e) {
                            zone.querySelector('.drop-content').style.display = 'none';

                            var preview = document.getElementById('preview_' + index);
                            preview.src = e.target.result;

                            var previewDiv = zone.querySelector('.drop-preview');
                            previewDiv.style.display = 'block';

                            zone.classList.add('has-file');
                        }
                        reader.readAsDataURL(file);
                    }
                });
            });
        </script>
        <?php if ($write_min || $write_max) { ?>
            <!-- 글자수 체크 알림 -->
            <div id="char_count_wrap"><span id="char_count"></span>글자</div>
        <?php } ?>

        <?php echo $editor_html; // 에디터 출력 ?>

        <div class="btn-group">
            <?php
            $cancel_url = get_pretty_url($bo_table);
            if (isset($_GET['me_code']))
                $cancel_url .= (strpos($cancel_url, '?') === false ? '?' : '&') . 'me_code=' . urlencode($_GET['me_code']);
            $cancel_url .= '#bo_cate'; // [Standard Standard (4.3)]
            ?>
            <a href="<?php echo $cancel_url; ?>" class="btn btn-cancel">Cancel</a>
            <button type="submit" id="btn_submit" accesskey="s" class="btn btn-submit">Publish</button>
        </div>
    </form>
</section>
</div>

<script>
    function fwrite_submit(f) {
        <?php echo $editor_js; // 에디터 사용시 자바스크립트에서 내용을 폼필드로 넣어주며 내용이 입력되었는지 검사함   ?>

        var subject = "";
        var content = "";
        $.ajax({
            url: g5_bbs_url + "/ajax.filter.php",
            type: "POST",
            data: {
                "subject": f.wr_subject.value,
                "content": f.wr_content.value
            },
            dataType: "json",
            async: false,
            cache: false,
            success: function (data, textStatus) {
                subject = data.subject;
                content = data.content;
            }
        });

        if (subject) {
            alert("제목에 금지단어('" + subject + "')가 포함되어있습니다");
            f.wr_subject.focus();
            return false;
        }

        if (content) {
            alert("내용에 금지단어('" + content + "')가 포함되어있습니다");
            if (typeof (ed_wr_content) != "undefined")
                ed_wr_content.returnFalse();
            else
                f.wr_content.focus();
            return false;
        }

        if (document.getElementById("char_count")) {
            if (char_min > 0 || char_max > 0) {
                var cnt = parseInt(check_byte("wr_content", "char_count"));
                if (char_min > 0 && char_min > cnt) {
                    alert("내용은 " + char_min + "글자 이상 쓰셔야 합니다.");
                    return false;
                }
                if (char_max > 0 && char_max < cnt) {
                    alert("내용은 " + char_max + "글자 이하로 쓰셔야 합니다.");
                    return false;
                }
            }
        }

        document.getElementById("btn_submit").disabled = "disabled";

        return true;
    }
</script>